<?php 
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<header id="header" class="block-header container-fluid">
    <div class="page-header-container">
    	<div class="header-top-part-row row">
    		<div class="header-top-part col-lg-12">
    			<div class="row">
    				<div class="col-md-6">
	    				<a class="logo" href="<?php echo $this->getUrl('') ?>">
			            	<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
			            	<img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
			        	</a> 
    				</div>
    				<div class="col-md-6">
				        <div class="skip-links">
				            <a href="#header-nav" class="skip-link skip-nav">
				                <span class="icon"></span>
				                <span class="label"><?php echo $this->__('Menu'); ?></span>
				            </a>
				
				            <a href="#header-search" class="skip-link skip-search">
				                <span class="icon"></span>
				                <span class="label"><?php echo $this->__('Search'); ?></span>
				            </a>
						    <div id="header-search" class="skip-content pull-right">
				            	<?php echo $this->getChildHtml('topSearch') ?>
				       		</div>				
				            <div class="account-cart-wrapper pull-right">
				                <a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" data-target-element="#header-account" class="skip-link skip-account">
				                    <span class="icon"></span>
				                    <span class="label"><?php echo $this->__('Account'); ?></span>
				                </a>
				
				                <!-- Cart -->
				
				                <div class="header-minicart">
				                    <?php echo $this->getChildHtml('minicart_head'); ?>
				                </div>
				            </div> 				
				        </div>    				
    				</div>
    			</div>
		        <!-- Account -->		
		        <div id="header-account" class="skip-content">
		            <?php echo $this->getChildHtml('topLinks') ?>
		        </div>
        	</div>
        </div>
     
		<div class="header-nav-row row">
			<div class="header-nav col-lg-12">
				    <!-- Navigation -->
		        <div id="header-nav" class="skip-content">
		            <?php echo $this->getChildHtml('topMenu') ?>
		        </div>
	        </div>
        </div>
        
    </div>
</header>
<div class="page-width container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<?php echo $this->getChildHtml('topContainer'); ?>
		</div>
	</div>
</div>
